language: node_js
node_js:
  - "0.12"
  - "0.10"
after_success:
  - npm run codecov

matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4"
    - node_js: "5"
notifications:
  email: false
sudo: false
